name: Mocha Unittests

on:
  push:
  pull_request:
      types: [ opened, synchronize, reopened ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    env:
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      PROMPT_CONTEXT: ${{ secrets.PROMPT_CONTEXT }}
      PROMPT_CONTEXT_DATA: ${{ secrets.PROMPT_CONTEXT_DATA }}
      PROMPT_INSTRUCTIONS: ${{ secrets.PROMPT_INSTRUCTIONS }}
      PROMPT_FEW_SHOTS_EXAMPLES: ${{ secrets.GEMINI_API_KEY }}
      AI_TEMPERATURE: ${{ secrets.AI_TEMPERATURE }}
      AI_TOP_P: ${{ secrets.AI_TOP_P }}
      AI_TOP_K: ${{ secrets.AI_TOP_K }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Compile TypeScript
        run: npm run build

      - name: Run tests
        run: npm run test
